version: "3.6"
services:
  chainlink:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "6688:6688"
    depends_on:
      - postgres
      - mock
    secrets:
      - node_password
      - apicredentials
      - keystore
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://chainlink@integration_postgres_1:5432/chainlink?sslmode=disable
    volumes:
      - 'cl:/chainlink'
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_MULTIPLE_DATABASES=chainlink,ei
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - './docker-init-scripts/postgres:/docker-entrypoint-initdb.d'
      - 'pg:/var/lib/postgresql/data'
  mock:
    build:
      context: ./mock-client
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - "SUBSCRIBED_ADDRESS=${SUBSCRIBED_ADDRESS}"
  external-initiator:
    build:
      context: ../.
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./external_initiator.env
    environment:
      - EI_DATABASEURL=postgresql://ei@integration_postgres_1:5432/ei?sslmode=disable
      - EI_CHAINLINKURL=http://integration_chainlink_1:6688/
    command:
      - '{"name":"eth-mock-http","type":"ethereum","url":"http://integration_mock_1:8080/eth","refreshInterval":600}'
      - '{"name":"eth-mock-ws","type":"ethereum","url":"ws://integration_mock_1:8080/ws/eth"}'
      - '{"name":"xtz-mock-http","type":"tezos","url":"http://integration_mock_1:8080/xtz","refreshInterval":600}'
volumes:
  pg:
  cl:
secrets:
  node_password:
    file: ./secrets/password.txt
  apicredentials:
    file: ./secrets/apicredentials
  keystore:
    file: ./secrets/0x9CA9d2D5E04012C9Ed24C0e513C9bfAa4A2dD77f.json
